name: martinomedia
description: Trigger dev build/deploy
filename: cloudbuild.yaml
github:
  owner: josepholiverr
  name: martinomedia 
  push:
    branch: ^prod$
substitutions:
  _REGION: us-central1
  _APP_NAME: martinomedia
  _BRANCH_NAME: prod

